namespace QLBH.Controls.Cửa_hàng
{
    partial class c03_nghiep_vu_cua_hang
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DevExpress.XtraEditors.TileItemElement tileItemElement41 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement42 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement43 = new DevExpress.XtraEditors.TileItemElement();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(c03_nghiep_vu_cua_hang));
            DevExpress.XtraEditors.TileItemFrame tileItemFrame17 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement44 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame18 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement45 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement46 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement47 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement48 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame19 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement49 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame20 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement50 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement51 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement52 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame21 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement53 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame22 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement54 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement55 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement56 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement57 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame23 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement58 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame24 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement59 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement60 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement61 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement62 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame25 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement63 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame26 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement64 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement65 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement66 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement67 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame27 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement68 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame28 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement69 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement70 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement71 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement72 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame29 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement73 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame30 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement74 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement75 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement76 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement77 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame31 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement78 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame32 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement79 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement80 = new DevExpress.XtraEditors.TileItemElement();
            this.tileItem14 = new DevExpress.XtraEditors.TileItem();
            this.tileItem5 = new DevExpress.XtraEditors.TileItem();
            this.m_tile_grp_khuyen_mai = new DevExpress.XtraEditors.TileGroup();
            this.m_tile_tao_khuyen_mai = new DevExpress.XtraEditors.TileItem();
            this.m_tile_cap_nhat_khuyen_mai = new DevExpress.XtraEditors.TileItem();
            this.m_tile_grp_phieu_nhap = new DevExpress.XtraEditors.TileGroup();
            this.m_tile_nhap_kho = new DevExpress.XtraEditors.TileItem();
            this.m_tile_thong_tin_ton_kho = new DevExpress.XtraEditors.TileItem();
            this.m_tile_grp_hoa_don = new DevExpress.XtraEditors.TileGroup();
            this.m_tile_them_ban_hang = new DevExpress.XtraEditors.TileItem();
            this.m_tile_tra_cuu_hoa_don = new DevExpress.XtraEditors.TileItem();
            this.m_tile_nghiep_vu = new DevExpress.XtraEditors.TileControl();
            this.SuspendLayout();
            // 
            // tileItem14
            // 
            tileItemElement41.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement41.Appearance.Hovered.Options.UseFont = true;
            tileItemElement41.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement41.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement41.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement41.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement41.Appearance.Normal.Options.UseFont = true;
            tileItemElement41.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement41.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement41.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement41.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement41.Appearance.Selected.Options.UseFont = true;
            tileItemElement41.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement41.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement41.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement41.MaxWidth = 160;
            tileItemElement41.Text = "Header";
            tileItemElement41.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement41.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement42.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement42.Appearance.Hovered.Options.UseFont = true;
            tileItemElement42.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement42.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement42.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement42.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement42.Appearance.Normal.Options.UseFont = true;
            tileItemElement42.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement42.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement42.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement42.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement42.Appearance.Selected.Options.UseFont = true;
            tileItemElement42.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement42.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement42.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement42.MaxWidth = 160;
            tileItemElement42.Text = "The quick brown fox jumps over the lazy dog.";
            tileItemElement42.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement42.TextLocation = new System.Drawing.Point(75, 27);
            tileItemElement43.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement43.Image")));
            tileItemElement43.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement43.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement43.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement43.ImageSize = new System.Drawing.Size(64, 64);
            this.tileItem14.Elements.Add(tileItemElement41);
            this.tileItem14.Elements.Add(tileItemElement42);
            this.tileItem14.Elements.Add(tileItemElement43);
            tileItemFrame17.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement44.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement44.Image")));
            tileItemElement44.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement44.ImageLocation = new System.Drawing.Point(-12, -8);
            tileItemElement44.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement44.ImageSize = new System.Drawing.Size(248, 120);
            tileItemFrame17.Elements.Add(tileItemElement44);
            tileItemFrame17.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame17.Image")));
            tileItemFrame18.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement45.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement45.Appearance.Hovered.Options.UseFont = true;
            tileItemElement45.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement45.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement45.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement45.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement45.Appearance.Normal.Options.UseFont = true;
            tileItemElement45.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement45.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement45.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement45.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement45.Appearance.Selected.Options.UseFont = true;
            tileItemElement45.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement45.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement45.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement45.MaxWidth = 160;
            tileItemElement45.Text = "Header";
            tileItemElement45.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement45.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement46.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement46.Appearance.Hovered.Options.UseFont = true;
            tileItemElement46.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement46.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement46.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement46.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement46.Appearance.Normal.Options.UseFont = true;
            tileItemElement46.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement46.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement46.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement46.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement46.Appearance.Selected.Options.UseFont = true;
            tileItemElement46.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement46.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement46.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement46.MaxWidth = 160;
            tileItemElement46.Text = "The quick brown fox jumps over the lazy dog.";
            tileItemElement46.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement46.TextLocation = new System.Drawing.Point(75, 27);
            tileItemElement47.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement47.Image")));
            tileItemElement47.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement47.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement47.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement47.ImageSize = new System.Drawing.Size(64, 64);
            tileItemFrame18.Elements.Add(tileItemElement45);
            tileItemFrame18.Elements.Add(tileItemElement46);
            tileItemFrame18.Elements.Add(tileItemElement47);
            this.tileItem14.Frames.Add(tileItemFrame17);
            this.tileItem14.Frames.Add(tileItemFrame18);
            this.tileItem14.Id = 9;
            this.tileItem14.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem14.Name = "tileItem14";
            // 
            // tileItem5
            // 
            tileItemElement48.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement48.Image")));
            tileItemElement48.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement48.ImageLocation = new System.Drawing.Point(-12, -8);
            tileItemElement48.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement48.ImageSize = new System.Drawing.Size(248, 120);
            this.tileItem5.Elements.Add(tileItemElement48);
            tileItemFrame19.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement49.Image = ((System.Drawing.Image)(resources.GetObject("tileItemElement49.Image")));
            tileItemElement49.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement49.ImageLocation = new System.Drawing.Point(-12, -8);
            tileItemElement49.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement49.ImageSize = new System.Drawing.Size(248, 120);
            tileItemFrame19.Elements.Add(tileItemElement49);
            tileItemFrame19.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame19.Image")));
            tileItemFrame20.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement50.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement50.Appearance.Hovered.Options.UseFont = true;
            tileItemElement50.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement50.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement50.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement50.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement50.Appearance.Normal.Options.UseFont = true;
            tileItemElement50.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement50.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement50.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement50.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement50.Appearance.Selected.Options.UseFont = true;
            tileItemElement50.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement50.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement50.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement50.Text = "Header";
            tileItemElement50.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement50.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement51.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement51.Appearance.Hovered.Options.UseFont = true;
            tileItemElement51.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement51.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement51.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement51.Appearance.Normal.Options.UseFont = true;
            tileItemElement51.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement51.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement51.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement51.Appearance.Selected.Options.UseFont = true;
            tileItemElement51.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement51.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement51.Text = "The quick brown fox jumps over the lazy dog.";
            tileItemElement51.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement51.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame20.Elements.Add(tileItemElement50);
            tileItemFrame20.Elements.Add(tileItemElement51);
            this.tileItem5.Frames.Add(tileItemFrame19);
            this.tileItem5.Frames.Add(tileItemFrame20);
            this.tileItem5.Id = 1;
            this.tileItem5.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem5.Name = "tileItem5";
            // 
            // m_tile_grp_khuyen_mai
            // 
            this.m_tile_grp_khuyen_mai.Items.Add(this.m_tile_tao_khuyen_mai);
            this.m_tile_grp_khuyen_mai.Items.Add(this.m_tile_cap_nhat_khuyen_mai);
            this.m_tile_grp_khuyen_mai.Name = "m_tile_grp_khuyen_mai";
            // 
            // m_tile_tao_khuyen_mai
            // 
            this.m_tile_tao_khuyen_mai.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(153)))), ((int)(((byte)(0)))));
            this.m_tile_tao_khuyen_mai.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement52.Image = global::QLBH.Properties.Resources.Sale_481;
            tileItemElement52.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement52.ImageLocation = new System.Drawing.Point(85, 25);
            tileItemElement52.ImageSize = new System.Drawing.Size(248, 120);
            this.m_tile_tao_khuyen_mai.Elements.Add(tileItemElement52);
            tileItemFrame21.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement53.Image = global::QLBH.Properties.Resources.Sale_481;
            tileItemElement53.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement53.ImageLocation = new System.Drawing.Point(85, 25);
            tileItemElement53.ImageSize = new System.Drawing.Size(248, 120);
            tileItemFrame21.Elements.Add(tileItemElement53);
            tileItemFrame21.Image = global::QLBH.Properties.Resources.Sale_481;
            tileItemFrame22.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement54.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement54.Appearance.Hovered.Options.UseFont = true;
            tileItemElement54.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement54.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement54.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement54.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement54.Appearance.Normal.Options.UseFont = true;
            tileItemElement54.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement54.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement54.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement54.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement54.Appearance.Selected.Options.UseFont = true;
            tileItemElement54.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement54.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement54.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement54.Text = "Tạo khuyến mãi";
            tileItemElement54.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement54.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement55.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement55.Appearance.Hovered.Options.UseFont = true;
            tileItemElement55.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement55.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement55.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement55.Appearance.Normal.Options.UseFont = true;
            tileItemElement55.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement55.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement55.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement55.Appearance.Selected.Options.UseFont = true;
            tileItemElement55.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement55.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement55.Text = "Thêm mới đợt khuyến mãi và các hàng hóa áp dụng";
            tileItemElement55.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement55.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame22.Elements.Add(tileItemElement54);
            tileItemFrame22.Elements.Add(tileItemElement55);
            this.m_tile_tao_khuyen_mai.Frames.Add(tileItemFrame21);
            this.m_tile_tao_khuyen_mai.Frames.Add(tileItemFrame22);
            this.m_tile_tao_khuyen_mai.Id = 18;
            this.m_tile_tao_khuyen_mai.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_tao_khuyen_mai.Name = "m_tile_tao_khuyen_mai";
            // 
            // m_tile_cap_nhat_khuyen_mai
            // 
            this.m_tile_cap_nhat_khuyen_mai.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(153)))), ((int)(((byte)(0)))));
            this.m_tile_cap_nhat_khuyen_mai.AppearanceItem.Normal.Options.UseBackColor = true;
            this.m_tile_cap_nhat_khuyen_mai.CurrentFrameIndex = 1;
            tileItemElement56.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement56.Appearance.Hovered.Options.UseFont = true;
            tileItemElement56.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement56.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement56.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement56.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement56.Appearance.Normal.Options.UseFont = true;
            tileItemElement56.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement56.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement56.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement56.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement56.Appearance.Selected.Options.UseFont = true;
            tileItemElement56.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement56.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement56.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement56.Text = "Cập nhật";
            tileItemElement56.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement57.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement57.Appearance.Hovered.Options.UseFont = true;
            tileItemElement57.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement57.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement57.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement57.Appearance.Normal.Options.UseFont = true;
            tileItemElement57.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement57.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement57.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement57.Appearance.Selected.Options.UseFont = true;
            tileItemElement57.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement57.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement57.Text = "Thay đổi thông tin, chính sách đợt khuyến mãi";
            tileItemElement57.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement57.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_cap_nhat_khuyen_mai.Elements.Add(tileItemElement56);
            this.m_tile_cap_nhat_khuyen_mai.Elements.Add(tileItemElement57);
            tileItemFrame23.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement58.Image = global::QLBH.Properties.Resources.Land_Sales_50;
            tileItemElement58.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement58.ImageLocation = new System.Drawing.Point(85, 25);
            tileItemElement58.ImageSize = new System.Drawing.Size(248, 120);
            tileItemFrame23.Elements.Add(tileItemElement58);
            tileItemFrame23.Image = global::QLBH.Properties.Resources.Land_Sales_50;
            tileItemFrame24.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement59.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement59.Appearance.Hovered.Options.UseFont = true;
            tileItemElement59.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement59.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement59.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement59.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement59.Appearance.Normal.Options.UseFont = true;
            tileItemElement59.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement59.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement59.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement59.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement59.Appearance.Selected.Options.UseFont = true;
            tileItemElement59.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement59.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement59.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement59.Text = "Cập nhật";
            tileItemElement59.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement60.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement60.Appearance.Hovered.Options.UseFont = true;
            tileItemElement60.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement60.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement60.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement60.Appearance.Normal.Options.UseFont = true;
            tileItemElement60.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement60.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement60.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement60.Appearance.Selected.Options.UseFont = true;
            tileItemElement60.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement60.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement60.Text = "Thay đổi thông tin, chính sách đợt khuyến mãi";
            tileItemElement60.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement60.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame24.Elements.Add(tileItemElement59);
            tileItemFrame24.Elements.Add(tileItemElement60);
            this.m_tile_cap_nhat_khuyen_mai.Frames.Add(tileItemFrame23);
            this.m_tile_cap_nhat_khuyen_mai.Frames.Add(tileItemFrame24);
            this.m_tile_cap_nhat_khuyen_mai.Id = 19;
            this.m_tile_cap_nhat_khuyen_mai.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_cap_nhat_khuyen_mai.Name = "m_tile_cap_nhat_khuyen_mai";
            // 
            // m_tile_grp_phieu_nhap
            // 
            this.m_tile_grp_phieu_nhap.Items.Add(this.m_tile_nhap_kho);
            this.m_tile_grp_phieu_nhap.Items.Add(this.m_tile_thong_tin_ton_kho);
            this.m_tile_grp_phieu_nhap.Name = "m_tile_grp_phieu_nhap";
            // 
            // m_tile_nhap_kho
            // 
            this.m_tile_nhap_kho.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(153)))), ((int)(((byte)(0)))));
            this.m_tile_nhap_kho.AppearanceItem.Normal.Options.UseBackColor = true;
            this.m_tile_nhap_kho.CurrentFrameIndex = 1;
            tileItemElement61.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement61.Appearance.Hovered.Options.UseFont = true;
            tileItemElement61.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement61.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement61.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement61.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement61.Appearance.Normal.Options.UseFont = true;
            tileItemElement61.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement61.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement61.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement61.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement61.Appearance.Selected.Options.UseFont = true;
            tileItemElement61.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement61.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement61.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement61.Text = "Thêm phiếu nhập ";
            tileItemElement61.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement61.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement62.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement62.Appearance.Hovered.Options.UseFont = true;
            tileItemElement62.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement62.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement62.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement62.Appearance.Normal.Options.UseFont = true;
            tileItemElement62.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement62.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement62.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement62.Appearance.Selected.Options.UseFont = true;
            tileItemElement62.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement62.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement62.Text = "Thêm phiếu nhập từ file Excel mẫu";
            tileItemElement62.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement62.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_nhap_kho.Elements.Add(tileItemElement61);
            this.m_tile_nhap_kho.Elements.Add(tileItemElement62);
            tileItemFrame25.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement63.Image = global::QLBH.Properties.Resources.MS_Excel_Filled_50;
            tileItemElement63.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement63.ImageLocation = new System.Drawing.Point(85, 25);
            tileItemElement63.ImageSize = new System.Drawing.Size(248, 120);
            tileItemFrame25.Elements.Add(tileItemElement63);
            tileItemFrame25.Image = global::QLBH.Properties.Resources.MS_Excel_Filled_50;
            tileItemFrame26.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement64.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement64.Appearance.Hovered.Options.UseFont = true;
            tileItemElement64.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement64.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement64.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement64.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement64.Appearance.Normal.Options.UseFont = true;
            tileItemElement64.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement64.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement64.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement64.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement64.Appearance.Selected.Options.UseFont = true;
            tileItemElement64.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement64.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement64.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement64.Text = "Thêm phiếu nhập ";
            tileItemElement64.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement64.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement65.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement65.Appearance.Hovered.Options.UseFont = true;
            tileItemElement65.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement65.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement65.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement65.Appearance.Normal.Options.UseFont = true;
            tileItemElement65.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement65.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement65.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement65.Appearance.Selected.Options.UseFont = true;
            tileItemElement65.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement65.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement65.Text = "Thêm phiếu nhập từ file Excel mẫu";
            tileItemElement65.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement65.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame26.Elements.Add(tileItemElement64);
            tileItemFrame26.Elements.Add(tileItemElement65);
            this.m_tile_nhap_kho.Frames.Add(tileItemFrame25);
            this.m_tile_nhap_kho.Frames.Add(tileItemFrame26);
            this.m_tile_nhap_kho.Id = 16;
            this.m_tile_nhap_kho.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_nhap_kho.Name = "m_tile_nhap_kho";
            // 
            // m_tile_thong_tin_ton_kho
            // 
            this.m_tile_thong_tin_ton_kho.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(153)))), ((int)(((byte)(0)))));
            this.m_tile_thong_tin_ton_kho.AppearanceItem.Normal.Options.UseBackColor = true;
            this.m_tile_thong_tin_ton_kho.CurrentFrameIndex = 1;
            tileItemElement66.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement66.Appearance.Hovered.Options.UseFont = true;
            tileItemElement66.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement66.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement66.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement66.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement66.Appearance.Normal.Options.UseFont = true;
            tileItemElement66.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement66.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement66.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement66.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement66.Appearance.Selected.Options.UseFont = true;
            tileItemElement66.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement66.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement66.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement66.Text = "Tồn kho";
            tileItemElement66.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement66.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement67.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement67.Appearance.Hovered.Options.UseFont = true;
            tileItemElement67.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement67.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement67.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement67.Appearance.Normal.Options.UseFont = true;
            tileItemElement67.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement67.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement67.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement67.Appearance.Selected.Options.UseFont = true;
            tileItemElement67.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement67.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement67.Text = "Xem và chỉnh sửa thông tin tồn kho";
            tileItemElement67.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement67.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_thong_tin_ton_kho.Elements.Add(tileItemElement66);
            this.m_tile_thong_tin_ton_kho.Elements.Add(tileItemElement67);
            tileItemFrame27.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement68.Image = global::QLBH.Properties.Resources.Box_Filled_50;
            tileItemElement68.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement68.ImageLocation = new System.Drawing.Point(85, 25);
            tileItemElement68.ImageSize = new System.Drawing.Size(248, 120);
            tileItemFrame27.Elements.Add(tileItemElement68);
            tileItemFrame27.Image = global::QLBH.Properties.Resources.Box_Filled_50;
            tileItemFrame28.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement69.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement69.Appearance.Hovered.Options.UseFont = true;
            tileItemElement69.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement69.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement69.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement69.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement69.Appearance.Normal.Options.UseFont = true;
            tileItemElement69.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement69.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement69.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement69.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement69.Appearance.Selected.Options.UseFont = true;
            tileItemElement69.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement69.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement69.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement69.Text = "Tồn kho";
            tileItemElement69.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement69.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement70.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement70.Appearance.Hovered.Options.UseFont = true;
            tileItemElement70.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement70.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement70.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement70.Appearance.Normal.Options.UseFont = true;
            tileItemElement70.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement70.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement70.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement70.Appearance.Selected.Options.UseFont = true;
            tileItemElement70.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement70.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement70.Text = "Xem và chỉnh sửa thông tin tồn kho";
            tileItemElement70.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement70.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame28.Elements.Add(tileItemElement69);
            tileItemFrame28.Elements.Add(tileItemElement70);
            this.m_tile_thong_tin_ton_kho.Frames.Add(tileItemFrame27);
            this.m_tile_thong_tin_ton_kho.Frames.Add(tileItemFrame28);
            this.m_tile_thong_tin_ton_kho.Id = 17;
            this.m_tile_thong_tin_ton_kho.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_thong_tin_ton_kho.Name = "m_tile_thong_tin_ton_kho";
            // 
            // m_tile_grp_hoa_don
            // 
            this.m_tile_grp_hoa_don.Items.Add(this.m_tile_them_ban_hang);
            this.m_tile_grp_hoa_don.Items.Add(this.m_tile_tra_cuu_hoa_don);
            this.m_tile_grp_hoa_don.Name = "m_tile_grp_hoa_don";
            // 
            // m_tile_them_ban_hang
            // 
            this.m_tile_them_ban_hang.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(153)))), ((int)(((byte)(0)))));
            this.m_tile_them_ban_hang.AppearanceItem.Normal.Options.UseBackColor = true;
            this.m_tile_them_ban_hang.CurrentFrameIndex = 1;
            tileItemElement71.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement71.Appearance.Hovered.Options.UseFont = true;
            tileItemElement71.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement71.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement71.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement71.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement71.Appearance.Normal.Options.UseFont = true;
            tileItemElement71.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement71.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement71.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement71.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement71.Appearance.Selected.Options.UseFont = true;
            tileItemElement71.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement71.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement71.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement71.Text = "Bán hàng";
            tileItemElement71.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement72.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement72.Appearance.Hovered.Options.UseFont = true;
            tileItemElement72.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement72.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement72.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement72.Appearance.Normal.Options.UseFont = true;
            tileItemElement72.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement72.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement72.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement72.Appearance.Selected.Options.UseFont = true;
            tileItemElement72.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement72.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement72.Text = "Thêm mới hóa đơn và lưu lại";
            tileItemElement72.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement72.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_them_ban_hang.Elements.Add(tileItemElement71);
            this.m_tile_them_ban_hang.Elements.Add(tileItemElement72);
            tileItemFrame29.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement73.Image = global::QLBH.Properties.Resources.Shopping_Cart_52__2_;
            tileItemElement73.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement73.ImageLocation = new System.Drawing.Point(80, 20);
            tileItemElement73.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Squeeze;
            tileItemElement73.ImageSize = new System.Drawing.Size(250, 100);
            tileItemFrame29.Elements.Add(tileItemElement73);
            tileItemFrame29.Image = global::QLBH.Properties.Resources.Shopping_Cart_52__2_;
            tileItemFrame30.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement74.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement74.Appearance.Hovered.Options.UseFont = true;
            tileItemElement74.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement74.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement74.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement74.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement74.Appearance.Normal.Options.UseFont = true;
            tileItemElement74.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement74.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement74.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement74.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement74.Appearance.Selected.Options.UseFont = true;
            tileItemElement74.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement74.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement74.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement74.Text = "Bán hàng";
            tileItemElement74.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement75.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement75.Appearance.Hovered.Options.UseFont = true;
            tileItemElement75.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement75.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement75.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement75.Appearance.Normal.Options.UseFont = true;
            tileItemElement75.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement75.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement75.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement75.Appearance.Selected.Options.UseFont = true;
            tileItemElement75.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement75.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement75.Text = "Thêm mới hóa đơn và lưu lại";
            tileItemElement75.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement75.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame30.Elements.Add(tileItemElement74);
            tileItemFrame30.Elements.Add(tileItemElement75);
            this.m_tile_them_ban_hang.Frames.Add(tileItemFrame29);
            this.m_tile_them_ban_hang.Frames.Add(tileItemFrame30);
            this.m_tile_them_ban_hang.Id = 9;
            this.m_tile_them_ban_hang.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_them_ban_hang.Name = "m_tile_them_ban_hang";
            // 
            // m_tile_tra_cuu_hoa_don
            // 
            this.m_tile_tra_cuu_hoa_don.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(153)))), ((int)(((byte)(0)))));
            this.m_tile_tra_cuu_hoa_don.AppearanceItem.Normal.Options.UseBackColor = true;
            this.m_tile_tra_cuu_hoa_don.CurrentFrameIndex = 1;
            tileItemElement76.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement76.Appearance.Hovered.Options.UseFont = true;
            tileItemElement76.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement76.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement76.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement76.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement76.Appearance.Normal.Options.UseFont = true;
            tileItemElement76.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement76.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement76.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement76.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement76.Appearance.Selected.Options.UseFont = true;
            tileItemElement76.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement76.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement76.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement76.Text = "Quản lý hóa đơn";
            tileItemElement76.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement76.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement77.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement77.Appearance.Hovered.Options.UseFont = true;
            tileItemElement77.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement77.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement77.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement77.Appearance.Normal.Options.UseFont = true;
            tileItemElement77.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement77.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement77.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement77.Appearance.Selected.Options.UseFont = true;
            tileItemElement77.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement77.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement77.Text = "Tra cứu, sửa, xóa thông tin hóa đơn";
            tileItemElement77.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement77.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_tra_cuu_hoa_don.Elements.Add(tileItemElement76);
            this.m_tile_tra_cuu_hoa_don.Elements.Add(tileItemElement77);
            tileItemFrame31.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement78.Image = global::QLBH.Properties.Resources.Bill_Filled_50__2_;
            tileItemElement78.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement78.ImageLocation = new System.Drawing.Point(85, 25);
            tileItemElement78.ImageSize = new System.Drawing.Size(248, 120);
            tileItemFrame31.Elements.Add(tileItemElement78);
            tileItemFrame31.Image = global::QLBH.Properties.Resources.Bill_Filled_50__2_;
            tileItemFrame32.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement79.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement79.Appearance.Hovered.Options.UseFont = true;
            tileItemElement79.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement79.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement79.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement79.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement79.Appearance.Normal.Options.UseFont = true;
            tileItemElement79.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement79.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement79.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement79.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement79.Appearance.Selected.Options.UseFont = true;
            tileItemElement79.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement79.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement79.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement79.Text = "Quản lý hóa đơn";
            tileItemElement79.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement79.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement80.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement80.Appearance.Hovered.Options.UseFont = true;
            tileItemElement80.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement80.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement80.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement80.Appearance.Normal.Options.UseFont = true;
            tileItemElement80.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement80.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement80.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement80.Appearance.Selected.Options.UseFont = true;
            tileItemElement80.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement80.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement80.Text = "Tra cứu, sửa, xóa thông tin hóa đơn";
            tileItemElement80.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement80.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame32.Elements.Add(tileItemElement79);
            tileItemFrame32.Elements.Add(tileItemElement80);
            this.m_tile_tra_cuu_hoa_don.Frames.Add(tileItemFrame31);
            this.m_tile_tra_cuu_hoa_don.Frames.Add(tileItemFrame32);
            this.m_tile_tra_cuu_hoa_don.Id = 10;
            this.m_tile_tra_cuu_hoa_don.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_tra_cuu_hoa_don.Name = "m_tile_tra_cuu_hoa_don";
            // 
            // m_tile_nghiep_vu
            // 
            this.m_tile_nghiep_vu.AppearanceGroupHighlighting.HoveredMaskColor = System.Drawing.Color.DimGray;
            this.m_tile_nghiep_vu.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.m_tile_nghiep_vu.AppearanceItem.Normal.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.ForwardDiagonal;
            this.m_tile_nghiep_vu.AppearanceItem.Normal.Options.UseBackColor = true;
            this.m_tile_nghiep_vu.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(67)))), ((int)(((byte)(67)))), ((int)(((byte)(67)))));
            this.m_tile_nghiep_vu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_tile_nghiep_vu.DragSize = new System.Drawing.Size(0, 0);
            this.m_tile_nghiep_vu.Groups.Add(this.m_tile_grp_hoa_don);
            this.m_tile_nghiep_vu.Groups.Add(this.m_tile_grp_phieu_nhap);
            this.m_tile_nghiep_vu.Groups.Add(this.m_tile_grp_khuyen_mai);
            this.m_tile_nghiep_vu.Location = new System.Drawing.Point(0, 0);
            this.m_tile_nghiep_vu.MaxId = 23;
            this.m_tile_nghiep_vu.Name = "m_tile_nghiep_vu";
            this.m_tile_nghiep_vu.Size = new System.Drawing.Size(919, 326);
            this.m_tile_nghiep_vu.TabIndex = 2;
            this.m_tile_nghiep_vu.Text = "tileControl3";
            // 
            // c03_nghiep_vu_cua_hang
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.m_tile_nghiep_vu);
            this.Name = "c03_nghiep_vu_cua_hang";
            this.Size = new System.Drawing.Size(919, 326);
            this.ResumeLayout(false);

        }

        #endregion
        private DevExpress.XtraEditors.TileItem tileItem5;
        private DevExpress.XtraEditors.TileItem tileItem14;
        private DevExpress.XtraEditors.TileGroup m_tile_grp_khuyen_mai;
        private DevExpress.XtraEditors.TileItem m_tile_tao_khuyen_mai;
        private DevExpress.XtraEditors.TileItem m_tile_cap_nhat_khuyen_mai;
        private DevExpress.XtraEditors.TileGroup m_tile_grp_phieu_nhap;
        private DevExpress.XtraEditors.TileItem m_tile_nhap_kho;
        private DevExpress.XtraEditors.TileItem m_tile_thong_tin_ton_kho;
        private DevExpress.XtraEditors.TileGroup m_tile_grp_hoa_don;
        private DevExpress.XtraEditors.TileItem m_tile_them_ban_hang;
        private DevExpress.XtraEditors.TileItem m_tile_tra_cuu_hoa_don;
        private DevExpress.XtraEditors.TileControl m_tile_nghiep_vu;
    }
}
